// Generated by the Supabase MCP (generate_typescript_types) against the
// sumg-garment-lab project (jigpokaqnfllvfkdxixq) schema in
// supabase/migrations/. Regenerate after schema changes instead of hand
// editing.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      candidate_regions: {
        Row: {
          analysis_id: string
          confidence: number | null
          created_at: string
          created_by: string
          height: number
          id: string
          label: string | null
          owner_id: string
          region_type: string
          source_id: string
          width: number
          x: number
          y: number
        }
        Insert: {
          analysis_id: string
          confidence?: number | null
          created_at?: string
          created_by?: string
          height: number
          id?: string
          label?: string | null
          owner_id?: string
          region_type: string
          source_id: string
          width: number
          x: number
          y: number
        }
        Update: {
          analysis_id?: string
          confidence?: number | null
          created_at?: string
          created_by?: string
          height?: number
          id?: string
          label?: string | null
          owner_id?: string
          region_type?: string
          source_id?: string
          width?: number
          x?: number
          y?: number
        }
        Relationships: [
          {
            foreignKeyName: "candidate_regions_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "creative_analyses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "candidate_regions_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "garment_sources"
            referencedColumns: ["id"]
          },
        ]
      }
      creative_analyses: {
        Row: {
          created_at: string
          error_code: string | null
          error_message: string | null
          id: string
          owner_id: string
          provider: string
          source_id: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          error_code?: string | null
          error_message?: string | null
          id?: string
          owner_id?: string
          provider?: string
          source_id: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          error_code?: string | null
          error_message?: string | null
          id?: string
          owner_id?: string
          provider?: string
          source_id?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "creative_analyses_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: true
            referencedRelation: "garment_sources"
            referencedColumns: ["id"]
          },
        ]
      }
      extractions: {
        Row: {
          candidate_region_id: string
          created_at: string
          created_by: string
          id: string
          owner_id: string
          source_id: string
          status: string
          storage_path: string | null
        }
        Insert: {
          candidate_region_id: string
          created_at?: string
          created_by?: string
          id?: string
          owner_id?: string
          source_id: string
          status?: string
          storage_path?: string | null
        }
        Update: {
          candidate_region_id?: string
          created_at?: string
          created_by?: string
          id?: string
          owner_id?: string
          source_id?: string
          status?: string
          storage_path?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "extractions_candidate_region_id_fkey"
            columns: ["candidate_region_id"]
            isOneToOne: false
            referencedRelation: "candidate_regions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "extractions_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "garment_sources"
            referencedColumns: ["id"]
          },
        ]
      }
      garment_sources: {
        Row: {
          byte_size: number
          created_at: string
          height_px: number | null
          id: string
          mime_type: string
          original_filename: string
          owner_id: string
          storage_bucket: string
          storage_path: string
          width_px: number | null
        }
        Insert: {
          byte_size: number
          created_at?: string
          height_px?: number | null
          id?: string
          mime_type: string
          original_filename: string
          owner_id?: string
          storage_bucket?: string
          storage_path: string
          width_px?: number | null
        }
        Update: {
          byte_size?: number
          created_at?: string
          height_px?: number | null
          id?: string
          mime_type?: string
          original_filename?: string
          owner_id?: string
          storage_bucket?: string
          storage_path?: string
          width_px?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
